# -*- coding: utf-8 -*-
"""
Cross-Agent Handoff Example for USMC
====================================

Demonstrates how two autonomous agents (e.g., 'claude' and 'gemini')
collaborate asynchronously via USMC shared memory without conflicts:

1. Agent A ('claude') executes an investigative phase:
   - Starts an active session.
   - Saves architectural facts and a diagnostic lesson.
   - Posts working status notes.
   - Ends the session with explicit handoff instructions for the next agent.

2. Agent B ('gemini') resumes the task:
   - Starts a session with task context.
   - Generates contextual markdown containing previous notes and lessons.
   - Retrieves shared facts and implements the solution.
   - Updates working memory and completes the handoff lifecycle.

Usage:
    python examples/cross_agent_handoff.py
"""

from pathlib import Path
import tempfile
from usmc.client import USMCClient


def run_handoff_demo(db_path: Path) -> None:
    print("=== USMC Cross-Agent Handoff Demo ===")
    print(f"Shared Database: {db_path}\n")

    # -------------------------------------------------------------
    # Phase 1: Agent 'claude' investigates and prepares the handoff
    # -------------------------------------------------------------
    print("--- Phase 1: Agent 'claude' starts work ---")
    client_a = USMCClient(db_path=db_path, agent_id="claude")

    session_a = client_a.start_session(task="Investigate database race conditions")
    print(f"Session #{session_a['id']} started for agent '{session_a['agent_id']}'")

    # Agent A records verified facts
    fact = client_a.add_fact(
        category="project",
        key="database_engine",
        value="SQLite with WAL mode and PRAGMA busy_timeout=5000",
        confidence=0.95,
    )
    print(f"Fact added: [{fact['category']}] {fact['key']} = {fact['value']}")

    # Agent A records a lesson learned
    lesson = client_a.add_lesson(
        title="SQLite Upsert Race",
        problem="Concurrent insert-if-not-exists queries can trigger integrity collisions.",
        solution="Use atomic INSERT INTO ... ON CONFLICT DO UPDATE SET (SQLite >= 3.24).",
        severity="high",
        category="database",
    )
    print(f"Lesson #{lesson['id']} recorded: {lesson['title']}")

    # Agent A records working progress
    client_a.add_working(
        content="Identified TOCTOU race in legacy put() logic. Need atomic upsert query.",
        type="note",
        priority=1,
    )

    # Agent A closes the session with explicit handoff notes
    handoff_text = (
        "Analysis complete. Architecture verified. Next agent: implement atomic "
        "upsert query and run full test suite."
    )
    client_a.end_session(session_id=session_a["id"], handoff_notes=handoff_text)
    print("Session ended with handoff notes recorded.\n")

    # -------------------------------------------------------------
    # Phase 2: Agent 'gemini' resumes work using the shared context
    # -------------------------------------------------------------
    print("--- Phase 2: Agent 'gemini' takes over ---")
    client_b = USMCClient(db_path=db_path, agent_id="gemini")

    session_b = client_b.start_session(
        task="Implement atomic upsert query based on claude handoff",
    )
    print(f"Session #{session_b['id']} started for agent '{session_b['agent_id']}'")

    # Agent B generates context from shared memory
    context_md = client_b.generate_context()
    print("\n--- Context Generated by USMC for Agent B ---")
    for line in context_md.strip().splitlines()[:10]:
        print(f"  {line}")
    print("  ...")

    # Agent B verifies facts recorded by Agent A
    facts = client_b.get_facts(category="project")
    print(f"\nAgent B retrieved {len(facts)} shared project fact(s):")
    for f in facts:
        print(f"  - [{f['agent_id']}] {f['key']}: {f['value']} (confidence: {f['confidence']})")

    # Agent B retrieves lessons recorded by Agent A
    lessons = client_b.get_lessons(severity="high")
    print(f"Agent B retrieved {len(lessons)} database lesson(s):")
    for item in lessons:
        print(f"  - {item['title']}: {item['solution']}")

    # Agent B updates working status
    client_b.add_working(
        content="Implemented atomic upsert in gardener.py; all 218 tests passing.",
        type="note",
        priority=2,
    )

    # Agent B concludes the task
    client_b.end_session(
        session_id=session_b["id"],
        handoff_notes="Task complete. Implementation verified and merged into main.",
    )
    print("\nAgent B finished session and marked handoff as completed successfully.")


def main() -> None:
    with tempfile.TemporaryDirectory() as temp_dir:
        demo_db = Path(temp_dir) / "handoff_demo.db"
        run_handoff_demo(demo_db)


if __name__ == "__main__":
    main()
